### ISSUE TITLE
No alfredworkflow in the release

### ISSUE THREAD

**Issue by guillaumeparis2000** [vincentezw/alfred-homeassistant#1]
Ther is no alfred workflow in the release. How I can install your workflow without this file?

**Comment by saeedesmaili** [comment]
@guillaumeparis2000 I created a new blank workflow, right click on the workflow and select "open in finder", then copy pasted the content of the zip file in the release into the workflow's directory. Here is an export if you're interested (zipped to be able to upload here, github doesn't allow uploading the workflow file here), but for sure, an alfred export would be nice in the release itself.
[alfred-homeassistant-1.0.zip](https://github.com/vincentezw/alfred-homeassistant/files/15045439/alfred-homeassistant-1.0.zip)
